language: node_js
sudo: false
node_js:
  - 8
  - 10
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn ci
notifications:
  email: false
after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
